spring.application.name=managers
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/managers
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Optional) kalau mau lihat log query lebih detail
logging.level.org.hibernate.SQL=debug

logging.file.name=./logs/filemanager-security.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
